import fs from "node:fs";
const platform = "server/platform.ts";
let p = fs.readFileSync(platform, "utf8");
if (!p.includes("validateSkillSwapListing")) {
  p += `\n\nexport type SkillSwapListingDraft = { title: string; description: string; availableSkills: string[]; learningGoals: string[]; durationMinutes: number; exchangeType: "skill_swap" | "paid"; priceBdt?: number | null };\n\nexport function validateSkillSwapListing(input: SkillSwapListingDraft) {\n  if (input.title.trim().length < 8 || input.title.trim().length > 120) throw new Error("Listing title must be between 8 and 120 characters");\n  if (input.description.trim().length < 20 || input.description.trim().length > 800) throw new Error("Listing description must be between 20 and 800 characters");\n  if (input.availableSkills.filter(Boolean).length === 0) throw new Error("At least one available skill is required");\n  if (input.learningGoals.filter(Boolean).length === 0) throw new Error("At least one learning goal is required");\n  if (!Number.isInteger(input.durationMinutes) || input.durationMinutes < 15 || input.durationMinutes > 480) throw new Error("Duration must be between 15 and 480 minutes");\n  if (input.exchangeType === "paid" && (input.priceBdt === undefined || input.priceBdt === null || input.priceBdt < 0)) throw new Error("A non-negative BDT price is required for paid listings");\n  return true;\n}\n`;
}
fs.writeFileSync(platform, p);
const test = "server/platform.test.ts";
let t = fs.readFileSync(test, "utf8");
t = t.replace('  sanitizeVerificationSubmission,', '  sanitizeVerificationSubmission,\n  validateSkillSwapListing,');
t = t.replace('  it("does not return a raw identity number from verification sanitization", () => {', '  it("requires meaningful skills and learning goals for a listing", () => {\n    expect(validateSkillSwapListing({ title: "Figma feedback for storytelling", description: "A focused exchange for reviewing one product flow and improving the story around it.", availableSkills: ["Figma"], learningGoals: ["Storytelling"], durationMinutes: 60, exchangeType: "skill_swap" })).toBe(true);\n    expect(() => validateSkillSwapListing({ title: "Too short", description: "A valid enough description that still has a useful length.", availableSkills: [], learningGoals: ["Writing"], durationMinutes: 60, exchangeType: "skill_swap" })).toThrow();\n    expect(() => validateSkillSwapListing({ title: "Paid service listing", description: "A paid listing with a useful description for a learner.", availableSkills: ["Design"], learningGoals: ["Feedback"], durationMinutes: 60, exchangeType: "paid" })).toThrow();\n  });\n\n  it("does not return a raw identity number from verification sanitization", () => {');
fs.writeFileSync(test, t);
